VALID_TOKENS = {
    ".",
    "wK", "wQ", "wR", "wB", "wN", "wP",
    "bK", "bQ", "bR", "bB", "bN", "bP"
}

BOARD_HEADER = "Board:"
COMMANDS_HEADER = "Commands:"
EMPTY_CELL = "."

CELL_SIZE = 100

WHITE = "w"
BLACK = "b"

KING = "K"
QUEEN = "Q"
ROOK = "R"
BISHOP = "B"
KNIGHT = "N"
PAWN = "P"

KING_MOVE_TIME = 1000
KNIGHT_MOVE_TIME = 3000
MOVE_TIME_PER_CELL = 1000

ERROR_ROW_WIDTH = "ERROR ROW_WIDTH_MISMATCH"
ERROR_UNKNOWN_TOKEN = "ERROR UNKNOWN_TOKEN"
